/* eslint-disable */
// GENERATED by scripts/extract-component-catalogue.js — do not edit.
// Regenerate: npm run tokens:docs

export interface CatalogueIndexEntry {
  key: string;
  name: string;
}

export interface CatalogueIndexGroup {
  id: string;
  title: string;
  components: CatalogueIndexEntry[];
}

export const componentCatalogueIndex: CatalogueIndexGroup[] = [
  {
    "id": "customized-primeng",
    "title": "Customized PrimeNG",
    "components": [
      {
        "key": "button",
        "name": "Button"
      },
      {
        "key": "inputs",
        "name": "Inputs"
      },
      {
        "key": "slider",
        "name": "Slider"
      },
      {
        "key": "textarea",
        "name": "Textarea"
      },
      {
        "key": "selects",
        "name": "Selects"
      },
      {
        "key": "checkbox-radios",
        "name": "Checkbox & Radios"
      },
      {
        "key": "chips",
        "name": "Chips"
      },
      {
        "key": "card",
        "name": "Card"
      },
      {
        "key": "datatable",
        "name": "DataTable"
      },
      {
        "key": "paginator",
        "name": "Paginator"
      },
      {
        "key": "tree",
        "name": "Tree"
      },
      {
        "key": "treetable",
        "name": "TreeTable"
      },
      {
        "key": "tabs",
        "name": "Tabs"
      },
      {
        "key": "breadcrumb",
        "name": "Breadcrumb"
      },
      {
        "key": "accordions",
        "name": "Accordions"
      },
      {
        "key": "menus",
        "name": "Menus"
      },
      {
        "key": "dialog",
        "name": "Dialog"
      },
      {
        "key": "drawer",
        "name": "Drawer"
      },
      {
        "key": "popover",
        "name": "Popover"
      },
      {
        "key": "toast",
        "name": "Toast"
      },
      {
        "key": "message",
        "name": "Message"
      },
      {
        "key": "tooltip",
        "name": "Tooltip"
      },
      {
        "key": "loading",
        "name": "Loading"
      }
    ]
  },
  {
    "id": "new-components",
    "title": "New components",
    "components": [
      {
        "key": "app-sidebar",
        "name": "AppSidebar"
      },
      {
        "key": "avatar",
        "name": "Avatar"
      },
      {
        "key": "chip",
        "name": "Chip"
      },
      {
        "key": "tag",
        "name": "Tag"
      },
      {
        "key": "badge",
        "name": "Badge"
      },
      {
        "key": "otp",
        "name": "OTP"
      },
      {
        "key": "stepper",
        "name": "Stepper"
      },
      {
        "key": "curinos-logo",
        "name": "Curinos Logo"
      },
      {
        "key": "ph-icon",
        "name": "Phosphor Icon"
      }
    ]
  },
  {
    "id": "primeng7-gap",
    "title": "PrimeNG 7 gap",
    "components": [
      {
        "key": "blockui",
        "name": "BlockUI"
      },
      {
        "key": "captcha",
        "name": "Captcha"
      },
      {
        "key": "carousel",
        "name": "Carousel"
      },
      {
        "key": "chart",
        "name": "Chart"
      },
      {
        "key": "colorpicker",
        "name": "ColorPicker"
      },
      {
        "key": "datascroller",
        "name": "DataScroller"
      },
      {
        "key": "dataview",
        "name": "DataView"
      },
      {
        "key": "fullcalendar",
        "name": "FullCalendar"
      },
      {
        "key": "galleria",
        "name": "Galleria"
      },
      {
        "key": "gmap",
        "name": "GMap"
      },
      {
        "key": "inplace",
        "name": "Inplace"
      },
      {
        "key": "orderlist",
        "name": "OrderList"
      },
      {
        "key": "organizationchart",
        "name": "OrganizationChart"
      },
      {
        "key": "picklist",
        "name": "PickList"
      },
      {
        "key": "rating",
        "name": "Rating"
      },
      {
        "key": "scrollpanel",
        "name": "ScrollPanel"
      },
      {
        "key": "terminal",
        "name": "Terminal"
      },
      {
        "key": "toolbar",
        "name": "Toolbar"
      },
      {
        "key": "virtualscroller",
        "name": "VirtualScroller"
      }
    ]
  }
];
