/* eslint-disable */
// GENERATED by scripts/extract-bridge-mappings.js — do not edit.
// Regenerate: npm run tokens:docs

export interface GeneratedTokenMapping {
  portion: string;
  bridge: string;
  curinos: string;
}

export interface GeneratedTransitionNote {
  title: string;
  body: string;
}

export interface GeneratedTransitionSection {
  key: string;
  title: string;
  approach: string;
  iframeHeight: number;
  tokenMappings: GeneratedTokenMapping[];
  notes: GeneratedTransitionNote[];
}

export interface GeneratedIconMapping {
  portion: string;
  bridge: string;
  curinos: string;
}

export const generatedTransitionData = {
  "sections": [
    {
      "key": "button",
      "title": "Button",
      "approach": "Global `.ui-button` selectors in `_overrides.scss`, scoped to `body:not(.primeng-default)`, consume Layer 2 `--primeng-button-*` tokens mapped to Curinos colors and dimensions.",
      "iframeHeight": 80,
      "notes": [],
      "tokenMappings": [
        {
          "portion": "Primary — background & border",
          "bridge": "--primeng-button-primary-background, --primeng-button-primary-border-color",
          "curinos": "--curinos-color-foreground-1"
        },
        {
          "portion": "Primary — label text",
          "bridge": "--primeng-button-primary-color",
          "curinos": "--curinos-color-background-1"
        },
        {
          "portion": "Primary — hover/active background & border",
          "bridge": "--primeng-button-primary-hover-background, --primeng-button-primary-hover-border-color",
          "curinos": "--curinos-color-semantic-primary-1"
        },
        {
          "portion": "Primary — hover/active label",
          "bridge": "--primeng-button-primary-hover-color",
          "curinos": "--curinos-color-foreground-1"
        },
        {
          "portion": "Secondary — border",
          "bridge": "--primeng-button-secondary-border-color",
          "curinos": "--curinos-color-foreground-2"
        },
        {
          "portion": "Secondary — label",
          "bridge": "--primeng-button-secondary-color",
          "curinos": "--curinos-color-foreground-1"
        },
        {
          "portion": "Secondary — hover background",
          "bridge": "--primeng-button-secondary-hover-background",
          "curinos": "--curinos-color-background-2"
        },
        {
          "portion": "Ghost — border",
          "bridge": "--primeng-button-ghost-border-color",
          "curinos": "--curinos-color-border-3"
        },
        {
          "portion": "Ghost — label",
          "bridge": "--primeng-button-ghost-color",
          "curinos": "--curinos-color-foreground-1"
        },
        {
          "portion": "Ghost — hover background & label",
          "bridge": "--primeng-button-ghost-hover-background, --primeng-button-ghost-hover-color",
          "curinos": "--curinos-color-background-2, --curinos-color-foreground-1"
        },
        {
          "portion": "All variants — border radius",
          "bridge": "--primeng-button-border-radius",
          "curinos": "--curinos-dimensions-radii-buttons"
        }
      ]
    },
    {
      "key": "input",
      "title": "InputText",
      "approach": "Single `.ui-inputtext` block in `_overrides.scss` replaces nova-light input chrome with Curinos tokens for background, border, padding, and typography.",
      "iframeHeight": 72,
      "notes": [],
      "tokenMappings": [
        {
          "portion": "Field background",
          "bridge": "--primeng-inputtext-background",
          "curinos": "--curinos-color-background-1"
        },
        {
          "portion": "Border (default)",
          "bridge": "--primeng-inputtext-border-color",
          "curinos": "--curinos-color-border-3"
        },
        {
          "portion": "Text",
          "bridge": "--primeng-inputtext-color",
          "curinos": "--curinos-color-foreground-2"
        },
        {
          "portion": "Placeholder",
          "bridge": "--primeng-inputtext-placeholder-color",
          "curinos": "--curinos-color-foreground-3"
        },
        {
          "portion": "Hover border",
          "bridge": "--primeng-inputtext-hover-border-color",
          "curinos": "--curinos-color-foreground-3"
        },
        {
          "portion": "Focus border",
          "bridge": "--primeng-inputtext-focus-border-color",
          "curinos": "--curinos-color-semantic-primary-1"
        },
        {
          "portion": "Border radius",
          "bridge": "--primeng-inputtext-border-radius",
          "curinos": "--curinos-dimensions-radii-inputs"
        }
      ]
    },
    {
      "key": "dropdown",
      "title": "Dropdown",
      "approach": "Dropdown overrides share input tokens for the closed state, then add panel-specific rules for the trigger, inner label, and popup item states.",
      "iframeHeight": 72,
      "notes": [],
      "tokenMappings": [
        {
          "portion": "Closed field — background, border, radius",
          "bridge": "--primeng-inputtext-background, --primeng-inputtext-border-color, --primeng-inputtext-border-radius",
          "curinos": "--curinos-color-background-1, --curinos-color-border-3, --curinos-dimensions-radii-inputs"
        },
        {
          "portion": "Closed field — hover/focus border",
          "bridge": "--primeng-inputtext-hover-border-color, --primeng-inputtext-focus-border-color",
          "curinos": "--curinos-color-foreground-3, --curinos-color-semantic-primary-1"
        },
        {
          "portion": "Placeholder label",
          "bridge": "--primeng-inputtext-placeholder-color",
          "curinos": "--curinos-color-foreground-3"
        },
        {
          "portion": "Selected value label",
          "bridge": "--primeng-inputtext-color",
          "curinos": "--curinos-color-foreground-2"
        },
        {
          "portion": "Chevron trigger icon",
          "bridge": "--primeng-dropdown-trigger-color",
          "curinos": "--curinos-color-foreground-3"
        },
        {
          "portion": "Panel item text",
          "bridge": "--primeng-dropdown-item-color",
          "curinos": "--curinos-color-foreground-2"
        },
        {
          "portion": "Panel item hover background & text",
          "bridge": "--primeng-dropdown-item-hover-background, --primeng-dropdown-item-hover-color",
          "curinos": "--curinos-color-background-2, --curinos-color-foreground-1"
        },
        {
          "portion": "Panel item selected background & text",
          "bridge": "--primeng-dropdown-item-selected-background, --primeng-dropdown-item-selected-color",
          "curinos": "--curinos-color-background-3, --curinos-color-foreground-1"
        }
      ]
    },
    {
      "key": "card",
      "title": "Card",
      "approach": "A single `.ui-card` override sets surface, border, radius, shadow, and resets inner part padding to 0. Opt-in layout modifiers (`ui-card--hero`, `ui-card--section`, etc.) in `_overrides.scss` re-apply padding via bridge tokens.",
      "iframeHeight": 140,
      "notes": [],
      "tokenMappings": [
        {
          "portion": "Surface background",
          "bridge": "--primeng-card-background",
          "curinos": "--curinos-color-semantic-surface-white"
        },
        {
          "portion": "Border",
          "bridge": "--primeng-card-border-color",
          "curinos": "--curinos-color-border-1"
        },
        {
          "portion": "Border radius",
          "bridge": "--primeng-card-border-radius",
          "curinos": "--curinos-dimensions-radii-cards"
        },
        {
          "portion": "Body text color",
          "bridge": "--primeng-card-color",
          "curinos": "--curinos-color-foreground-1"
        },
        {
          "portion": "Shadow",
          "bridge": "--primeng-card-shadow",
          "curinos": "0 1px 1.5px rgba(0, 0, 0, 0.1), 0 1px 1px rgba(0, 0, 0, 0.1)"
        },
        {
          "portion": "Hero body padding (`ui-card--hero`)",
          "bridge": "--primeng-card-hero-padding",
          "curinos": "32px 24px"
        },
        {
          "portion": "Section header padding (`ui-card--section`)",
          "bridge": "--primeng-card-section-header-padding",
          "curinos": "24px 24px 0"
        },
        {
          "portion": "Section content padding",
          "bridge": "--primeng-card-section-content-padding",
          "curinos": "24px"
        },
        {
          "portion": "Compact body padding (`ui-card--compact`)",
          "bridge": "--primeng-card-compact-padding",
          "curinos": "16px"
        }
      ]
    },
    {
      "key": "panelmenu",
      "title": "PanelMenu",
      "approach": "The heaviest override: resets nova-light accordion chrome (blue expanded headers, gray borders) and restyles the sidebar navigation to match Figma, scoped via `.sidebar-menu.ui-panelmenu`.",
      "iframeHeight": 200,
      "notes": [
        {
          "title": "PanelMenu expand icon swap",
          "body": "PrimeNG 7 PanelMenu hardcodes expand/collapse chevrons as PrimeIcons (pi-chevron-right, pi-chevron-down) on .ui-panelmenu-icon — they cannot be changed via MenuItem.icon. In the Curinos sidebar (.sidebar-menu), _overrides.scss replaces the glyph via ::before: Phosphor regular plus when collapsed, minus when the header has ui-state-active (expanded)."
        }
      ],
      "tokenMappings": [
        {
          "portion": "Section header & item text (default)",
          "bridge": "--primeng-panelmenu-item-color",
          "curinos": "--curinos-color-foreground-3"
        },
        {
          "portion": "Header & item hover/active background",
          "bridge": "--primeng-panelmenu-item-active-background",
          "curinos": "--curinos-color-background-2"
        },
        {
          "portion": "Header hover text",
          "bridge": "--primeng-panelmenu-item-hover-color",
          "curinos": "--curinos-color-foreground-1"
        },
        {
          "portion": "Active submenu item text",
          "bridge": "--primeng-panelmenu-item-active-color",
          "curinos": "--curinos-color-foreground-1"
        },
        {
          "portion": "Expand icon — plus/minus (::before on .ui-panelmenu-icon)",
          "bridge": "--primeng-panelmenu-icon-color",
          "curinos": "--curinos-color-foreground-3 (Phosphor regular via CSS swap replaces PrimeIcon chevrons)"
        },
        {
          "portion": "Duotone icon active fill (::before)",
          "bridge": "--primeng-panelmenu-icon-active-fill",
          "curinos": "--curinos-color-semantic-primary-1"
        },
        {
          "portion": "Duotone icon active stroke (::after)",
          "bridge": "--primeng-panelmenu-icon-active-stroke",
          "curinos": "--curinos-color-foreground-1"
        },
        {
          "portion": "Submenu left border",
          "bridge": "--primeng-panelmenu-border-color",
          "curinos": "--curinos-color-border-1"
        }
      ]
    },
    {
      "key": "datatable",
      "title": "DataTable",
      "approach": "Global `.ui-table` selectors in `_overrides.scss` restyle PrimeNG 7 `p-table` chrome — header row, body cells, zebra striping, hover, and sortable column states — via Layer 2 `--primeng-table-*` tokens.",
      "iframeHeight": 220,
      "notes": [],
      "tokenMappings": [
        {
          "portion": "Header background",
          "bridge": "--primeng-table-header-background",
          "curinos": "--curinos-color-background-2"
        },
        {
          "portion": "Header text",
          "bridge": "--primeng-table-header-color",
          "curinos": "--curinos-color-foreground-1"
        },
        {
          "portion": "Header bottom border",
          "bridge": "--primeng-table-header-border-color",
          "curinos": "--curinos-color-border-1"
        },
        {
          "portion": "Body row background",
          "bridge": "--primeng-table-body-background",
          "curinos": "--curinos-color-semantic-surface-white"
        },
        {
          "portion": "Zebra stripe row background",
          "bridge": "--primeng-table-row-stripe-background",
          "curinos": "--curinos-color-background-1"
        },
        {
          "portion": "Row hover background",
          "bridge": "--primeng-table-row-hover-background",
          "curinos": "--curinos-color-background-2"
        },
        {
          "portion": "Cell text",
          "bridge": "--primeng-table-cell-color",
          "curinos": "--curinos-color-foreground-2"
        },
        {
          "portion": "Cell bottom border",
          "bridge": "--primeng-table-border-color",
          "curinos": "--curinos-color-border-1"
        },
        {
          "portion": "Sort icon (default)",
          "bridge": "--primeng-table-sort-icon-color",
          "curinos": "--curinos-color-foreground-3"
        },
        {
          "portion": "Sort icon (active column)",
          "bridge": "--primeng-table-sort-icon-active-color",
          "curinos": "--curinos-color-foreground-1"
        }
      ]
    }
  ],
  "iconMappings": [
    {
      "portion": "Button icon (inherits label color)",
      "bridge": "color on .ui-button",
      "curinos": "--curinos-color-background-1 (primary), --curinos-color-foreground-1 (secondary/ghost)"
    },
    {
      "portion": "SVG icon stroke (regular/light)",
      "bridge": "stroke-width on <app-ph-icon>",
      "curinos": "--curinos-dimensions-icons-stroke"
    },
    {
      "portion": "PanelMenu expand icon (plus/minus)",
      "bridge": "--primeng-panelmenu-icon-color on .ui-panelmenu-icon::before",
      "curinos": "--curinos-color-foreground-3 (Phosphor regular via CSS swap — see PanelMenu section note)"
    }
  ]
} as {
  sections: GeneratedTransitionSection[];
  iconMappings: GeneratedIconMapping[];
};
